# Generated by Django 2.0.1 on 2018-01-28 01:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journee', '0002_auto_20180128_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interested_points', models.ManyToManyField(to='journee.PointOfInterest')),
            ],
        ),
        migrations.RemoveField(
            model_name='travelgroup',
            name='interested_points',
        ),
        migrations.RemoveField(
            model_name='travelgroup',
            name='iternary',
        ),
        migrations.RemoveField(
            model_name='travelgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place_id',
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journee.PointOfInterest'),
        ),
        migrations.AddField(
            model_name='event',
            name='proposed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journee.Traveler'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='TravelGroup',
        ),
        migrations.AddField(
            model_name='trip',
            name='itinerary',
            field=models.ManyToManyField(to='journee.Event'),
        ),
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(to='journee.Traveler'),
        ),
    ]
